### ISSUE TITLE
font-size not respected

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#2352]
## Description

I would like to specify a (minimum) font size for GTK elements and retain the ability to zoom in out in the text view. Unfortunately, the following does not work correctly:

```css
* {
  font-family: 'Arial', sans-serif;
  font-size: 17pt;
  color: red;
}

#zim-pageview text{
  font-family: 'Arial', sans-serif;
/*  font-size: when specified, prevents zoom */
/*  font-size: is not respected, but color is */
  font-size: 18pt; 
  color: green;
}
```

1. using the universal selector `*` **does** set the font size for everything, but I **lose** the ability to **zoom** in text view.
2. further specifying `zim-pageview` can **not** change font size, though it can change color, and does not re-enable ability to zoom text view.

## Environment

zim: 0.751 and latest Github
os: macOS 13.3.1 22E261 arm64
lang: english
